tech(OV-1074): upgrade php to 8.1
shippeo/monolog-extra pull request #4
Opened 2023-10-04 13:39 UTC by melvis-lr

Link https://shippeo.atlassian.net/browse/OV-1074

2023-10-04 13:43 UTC, Kleinast requested changes

2023-10-04 13:43 UTC, Kleinast commented on composer.json
> +    "php": "^8.1",
```suggestion
    "php": "^7.2||^8.1",
```

2023-10-04 13:43 UTC, Kleinast commented on composer.json
> +    "php": "^8.1",
si on peux avoir la double compatibilité ce serai bien d'avoir une version de transition

2023-10-04 14:13 UTC, melvis-lr commented on composer.json
> +    "php": "^8.1",
46bf9eb7fbbb489dafe6cf708b9402f5fe9ef20f

2023-10-04 15:01 UTC, Kleinast requested changes
@melvis-lr un retour de Alexis sur le ticket https://shippeo.atlassian.net/browse/OV-627?focusedCommentId=21346&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21346 pourrai tu du coup dans la foulée voir si tu peux passer le require du monolog en 3.x ou a minima en 2.9.x pour que le package googleapi puisse être upgrde également ?

2023-10-04 16:08 UTC, melvis-lr commented
@Kleinast 

> @melvis-lr un retour de Alexis sur le ticket https://shippeo.atlassian.net/browse/OV-627?focusedCommentId=21346&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21346 pourrai tu du coup dans la foulée voir si tu peux passer le require du monolog en 3.x ou a minima en 2.9.x pour que le package googleapi puisse être upgrde également ?

https://github.com/shippeo/monolog-extra/pull/4/commits/b624d91a4cccd84b38413cd6584d9b3a70c23bd3

2023-10-09 08:58 UTC, Kleinast approved these changes

2023-10-10 15:24 UTC, johnduro approved these changes

2023-10-10 15:56 UTC, merged